### ISSUE TITLE
bug: configuring publishing fails with "PublishingExtension does not exist"

### ISSUE THREAD

**Issue by JeremyStarTM** [solo-studios/nyx#1]
I'm using Gradle 8.10.2 (Kotlin DSL) with Nyx 0.2.3 from https://maven.solo-studios.ca/releases/ and am trying to configure publishing for my multiproject build using this code (snippet):

```kotlin
nyx {
    // [...]
    
    publishing {
        withPublish()
        repositories {
            reposiliteMaven("https://mvn.staropensource.de/engine") {
                name = "staropensource-engine"
                credentials(PasswordCredentials::class)
            }
        }
    }
    
    // [...]
}
```

I'm getting this error (shortened unfortunately, GitHub won't let me put the extremely long, complete stacktrace into a `<details>` block):
```plain
org.gradle.internal.exceptions.LocationAwareException: Build file '/home/jeremystartm/Code/StarOpenSource/Main/Engine/build.gradle.kts' line: 113
Extension of type 'PublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestingExtension, KotlinJvmProjectExtension, KotlinTestsRegistry, GitPropertiesPluginExtension, NyxExtension]
	<gradle code>
	at Program.execute(Unknown Source)
	<gradle code>
	at Program.execute(Unknown Source)
	<gradle code>
	<java code>
Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'PublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestingExtension, KotlinJvmProjectExtension, KotlinTestsRegistry, GitPropertiesPluginExtension, NyxExtension]
	<gradle code>
	at ca.solostudios.nyx.internal.util.GradleUtilKt.publishing(GradleUtil.kt:197)
	at ca.solostudios.nyx.plugin.publish.NyxPublishingExtension.repositories(NyxPublishingExtension.kt:133)
	at Build_gradle$1$1$2.execute(build.gradle.kts:113)
	at Build_gradle$1$1$2.execute(build.gradle.kts:111)
	<gradle code>
	at Build_gradle$1$1.execute(build.gradle.kts:111)
	at Build_gradle$1$1.execute(build.gradle.kts:73)
	<gradle code>
	at Build_gradle$1.execute(build.gradle.kts:73)
	at Build_gradle$1.execute(build.gradle.kts:65)
	<gradle code>
	at Build_gradle.<init>(build.gradle.kts:65)
	... 194 more



org.gradle.internal.exceptions.LocationAwareException: Build file '/home/jeremystartm/Code/StarOpenSource/Main/Engine/build.gradle.kts' line: 113
Extension of type 'PublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestingExtension, KotlinJvmProjectExtension, KotlinTestsRegistry, GitPropertiesPluginExtension, NyxExtension]
	<gradle code>
	at Program.execute(Unknown Source)
	<gradle code>
	at Program.execute(Unknown Source)
	<gradle code>
	<java code>
Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'PublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestingExtension, KotlinJvmProjectExtension, KotlinTestsRegistry, GitPropertiesPluginExtension, NyxExtension]
	<gradle code>
	at ca.solostudios.nyx.internal.util.GradleUtilKt.publishing(GradleUtil.kt:197)
	at ca.solostudios.nyx.plugin.publish.NyxPublishingExtension.repositories(NyxPublishingExtension.kt:133)
	at Build_gradle$1$1$2.execute(build.gradle.kts:113)
	at Build_gradle$1$1$2.execute(build.gradle.kts:111)
	<gradle code>
	at Build_gradle$1$1.execute(build.gradle.kts:111)
	at Build_gradle$1$1.execute(build.gradle.kts:73)
	<gradle code>
	at Build_gradle$1.execute(build.gradle.kts:73)
	at Build_gradle$1.execute(build.gradle.kts:65)
	<gradle code>
	at Build_gradle.<init>(build.gradle.kts:65)
	... 194 more



org.gradle.internal.exceptions.LocationAwareException: Build file '/home/jeremystartm/Code/StarOpenSource/Main/Engine/build.gradle.kts' line: 113
Extension of type 'PublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestingExtension, KotlinJvmProjectExtension, KotlinTestsRegistry, GitPropertiesPluginExtension, NyxExtension]
	<gradle code>
	at Program.execute(Unknown Source)
	<gradle code>
	at Program.execute(Unknown Source)
	<gradle code>
	<java code>
Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'PublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestingExtension, KotlinJvmProjectExtension, KotlinTestsRegistry, GitPropertiesPluginExtension, NyxExtension]
	<gradle code>
	at ca.solostudios.nyx.internal.util.GradleUtilKt.publishing(GradleUtil.kt:197)
	at ca.solostudios.nyx.plugin.publish.NyxPublishingExtension.repositories(NyxPublishingExtension.kt:133)
	at Build_gradle$1$1$2.execute(build.gradle.kts:113)
	at Build_gradle$1$1$2.execute(build.gradle.kts:111)
	<gradle code>
	at Build_gradle$1$1.execute(build.gradle.kts:111)
	at Build_gradle$1$1.execute(build.gradle.kts:73)
	<gradle code>
	at Build_gradle$1.execute(build.gradle.kts:73)
	at Build_gradle$1.execute(build.gradle.kts:65)
	<gradle code>
	at Build_gradle.<init>(build.gradle.kts:65)
	... 194 more
```

Seems to be caused by `publishing {}`, could not investigate far due to IntelliJ IDEA's bad reference detection when it comes to Gradle.

**Comment by JeremyStarTM** [comment]
Committed my changes, here's the full source: https://git.staropensource.de/StarOpenSource/Engine/src/commit/a2db3c3278e685dc83889a90d74b798a638a3317/build.gradle.kts#L114

**Comment by solonovamax** [comment]
hmm, it seems the issue occurs due to the `maven-publish` plugin not having been added
you could fix that by just adding 
```kotlin
plugins {
    `maven-publish`
}
```
to your buildscript, or in your case,
```
apply(plugin = "maven-publish")
```

I should probably make it so that if you invoke the `repositories` method, it always makes sure that `maven-publish` is loaded. even though I load it in the `configureProject` method, this only gets invoked during the `afterEvaluate` stage

**Comment by JeremyStarTM** [comment]
Worked, thanks!
